# Generated by Django 5.1.4 on 2025-03-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_salary_remove_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.TextField(default='Fresher'),
        ),
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.CharField(default='Bachelor', max_length=100),
        ),
    ]
