# Generated by Django 5.1.4 on 2025-03-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_application_experience_application_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(default='Fresher', max_length=100),
        ),
    ]
