# Generated by Django 5.1.4 on 2025-03-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_interview_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='invitation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='interview',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
